artifact_root: artifact

data_ingestion:
     root_dir: artifact/data_ingestion
     source_url: https://drive.google.com/file/d/1jPY9m9EoatwX5QOjOqBJ4t-fKvjlLvjh/view?usp=sharing
     local_data_files: artifact/data_ingestion/data.zip
     unzip_dir: artifact/data_ingestion




